server:
  port: 80

#Eureka配置
eureka:
  client:
    register-with-eureka: false # 表示是否向服务器注册自己,服务器要设置为false
    service-url: # 监控页面的地址 访问:http://${eureka.instance.hostname}:${server.port} 可以查看控制台
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #[集群(关联)]
